language: python
python:
  - "3.7-dev"

install:
  - pip install -r requirements.txt

script:
  - pylint answers_service/config answers_service/models answers_service/serializers answers_service/views setup.py

ignore:
  - answers_service.tests.test_flask_app